FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN apk add --no-cache curl
RUN npm install --force

COPY hardhat.config.js ./
COPY contracts ./contracts

RUN npx hardhat compile

EXPOSE 8545

CMD ["npx", "hardhat", "node", "--hostname", "0.0.0.0"]
